repos:
  - repo: local
    hooks:
    - id: terraform-fmt
      name: terraform fmt
      entry: terraform fmt -recursive
      language: system
      pass_filenames: false
    - id: terraform-validate
      name: terraform validate
      entry: terraform validate
      language: system
      pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-xml
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: pretty-format-java
        args:
          - --autofix
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.19.2
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.10.0
    hooks:
      - id: hadolint
        args: [ --ignore, DL3045 ]
