apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gitops-deploy
spec:
  eventBusName: monitoredrepo-eventbus
  # This is supposedly only for testing
  #service:
  #  ports:
  #    - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-reposrc:
      events:
        - push
      repositories:
#        - owner: <owner>
#            - <repoName>
         - owner: tpayne
           names:
            - argo-suite-samples
      webhook:
        port: '80'
        method: POST
        endpoint: >-
          /webhooks/gitops-deploy/github-reposrc
        # You will need to customise this as appropriate
        url: http://frontend.34-28-28-110.nip.io
      active: true
      insecure: true
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
